name: Publish

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: yarn install --frozen-lockfile
      - run: yarn ci
        env:
          SNYK_TOKEN: ${{secrets.SNYK_TOKEN}}

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
          always-auth: true
      - run: yarn install --frozen-lockfile
      - run: yarn publish
        env:
          SNYK_TOKEN: ${{secrets.SNYK_TOKEN}}
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
